import * as pdfjs from '../../lib/pdfjs.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc = chrome.runtime.getURL('lib/pdfjs.worker.min.mjs');
const { h, download } = UI;
const body = document.getElementById('studioBody');
let dispose = () => {};
const routes = { merge:'merge',split:'split',reorder:'reorder',extract:'extract',remove:'remove',reverse:'reverse',rotate:'rotate',watermark:'watermark',numbers:'numbers',resize:'resize',crop:'crop',blank:'blank',metadata:'metadata',flatten:'flatten',attach:'attach',optimize:'optimize' };
const link = (route,title,desc,icon)=>h('a',{class:'pdf-home-card',href:'#'+route},h('span',{'aria-hidden':'true'},icon),h('h3',{},title),h('p',{},desc));
async function render() {
  dispose(); dispose=()=>{}; body.replaceChildren();
  const hash=location.hash.slice(1)||'home'; const mode=hash.split('?')[0]; const requested=new URLSearchParams(hash.split('?')[1]||'').get('mode');
  document.querySelectorAll('.pdf-nav a').forEach(a=>a.classList.toggle('on',a.dataset.route===mode));
  if(mode==='home') { body.append(h('section',{class:'pdf-home-hero'},h('span',{class:'pdf-eyebrow'},'PRISM · PRIVATE PDF TOOLS'),h('h1',{},'A little less paperwork. A lot more possibility.'),h('p',{},'Organize, sign and finish documents in your browser. Your files stay on your device.')),
    h('div',{class:'pdf-home-grid'},link('merge','Merge PDFs','Put files together in your chosen order.','⊞'),link('split','Split PDF','Make smaller PDFs from selected pages.','⑂'),link('reorder','Organize pages','Rearrange, remove or duplicate pages.','⇄'),link('sign','Fill & sign','Place a signature directly on the page.','✍'),link('img2pdf','Images to PDF','Turn photos and scans into a PDF.','▧'),link('pdf','All PDF tools','Find watermark, page numbers, crop and more.','✦')));return; }
  const title=h('h1',{id:'title'},mode==='sign'?'Fill & sign PDF':mode==='img2pdf'?'Images to PDF':mode==='compress'?'Compress image':'PDF Studio');
  const sub=h('p',{id:'sub',class:'muted'},mode==='sign'?'Position a visual signature on the document. Review it before you download.':'Everything runs locally in this browser.');
  body.append(title,sub);
  if(mode==='sign') { await sign(body); return; }
  const spec = routes[mode] ? T.secs.pdf : mode==='pdf' ? T.secs.pdf : mode==='img2pdf' ? T.secs.img2pdf : mode==='compress' ? T.secs.compress : null;
  if(!spec) { location.replace('#home'); return; }
  if(spec.feature && !T.settings.on[spec.feature]) { body.append(h('p',{},'This tool is off. ',h('a',{href:'../options/options.html#'+spec.feature},'Turn it on in Settings')));return; }
  await spec.render(body,new URLSearchParams('mode='+(routes[mode]||requested||'merge')));
  dispose=()=>{for(const fn of T.cleanups.splice(0))fn();};
}
async function sign(target) {
  if(!T.settings.on.pdfsign) { target.append(h('a',{href:'../options/options.html#pdfsign'},'Turn on Fill & sign in Settings'));return; }
  let bytes, filename='', pdf, display, pageCount=0, pageNo=1, marks=[], drawn=false, busy=false, inputUrl;
  const status=h('p',{class:'studio-status',role:'status','aria-live':'polite'},'Add an unencrypted PDF to begin.');
  const canvas=h('canvas',{'aria-label':'PDF page preview'}), pageBox=h('div',{class:'sign-page'},canvas), documentBox=h('div',{class:'sign-document'});
  const pageLabel=h('strong',{},'Page 0 of 0'), prev=h('button',{class:'btn small',disabled:true,onclick:()=>{pageNo--;drawPage();}},'←'), next=h('button',{class:'btn small',disabled:true,onclick:()=>{pageNo++;drawPage();}},'→');
  documentBox.append(h('div',{class:'sign-preview-toolbar'},prev,pageLabel,next,h('span',{class:'grow'}),h('span',{class:'sign-mini'},'Drag to move · corner to resize')),pageBox);
  const signature=h('canvas',{width:600,height:180,class:'stage','aria-label':'Draw a signature'});const pen=signature.getContext('2d');pen.strokeStyle='#27347b';pen.lineWidth=3;pen.lineCap='round';let painting=false;
  const coords=e=>{const r=signature.getBoundingClientRect();return [(e.clientX-r.left)*600/r.width,(e.clientY-r.top)*180/r.height];};
  signature.onpointerdown=e=>{painting=true;signature.setPointerCapture(e.pointerId);pen.beginPath();pen.moveTo(...coords(e));};
  signature.onpointermove=e=>{if(painting){pen.lineTo(...coords(e));pen.stroke();drawn=true;}};signature.onpointerup=signature.onpointercancel=()=>painting=false;
  const typed=h('input',{placeholder:'Or type your name',maxlength:45,'aria-label':'Type signature'});
  typed.oninput=()=>{pen.clearRect(0,0,600,180);pen.fillStyle='#27347b';pen.font='italic 48px cursive';pen.fillText(typed.value,20,110,560);drawn=!!typed.value;};
  const imageInput=h('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'Upload signature image'});
  imageInput.onchange=async()=>{const f=imageInput.files?.[0];if(!f)return;if(f.size>5*1024*1024){status.textContent='Use an image below 5 MB.';return;}try{const img=new Image();const url=URL.createObjectURL(f);try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});pen.clearRect(0,0,600,180);const scale=Math.min(560/img.width,145/img.height);pen.drawImage(img,20,17,img.width*scale,img.height*scale);drawn=true;typed.value='';}finally{URL.revokeObjectURL(url);}}catch{status.textContent='Could not read that image.';}};
  const scope=h('select',{'aria-label':'Apply signature to pages'},h('option',{value:'current'},'This page'),h('option',{value:'all'},'All pages'),h('option',{value:'selected'},'Selected pages'));
  const range=h('input',{placeholder:'For example 1, 3-5','aria-label':'Selected page numbers',hidden:true});
  scope.onchange=()=>range.hidden=scope.value!=='selected';
  const formFields=h('div',{class:'sign-fields'}),output=h('div',{class:'sign-results'});
  const place=h('button',{class:'btn primary',disabled:true,onclick:()=>{if(!drawn)return UI.toast('Draw, type or upload a signature first.');const w=.32,hgt=Math.min(.2,w*180/600*pageBox.clientWidth/pageBox.clientHeight);const rect={page:pageNo,x:.17,y:.73,w,h:hgt,data:signature.toDataURL('image/png'),scope:scope.value,range:range.value};marks.push(rect);drawMarks();UI.toast('Signature placed. Drag it where you want.');}},'Place signature on page');
  const exportButton=h('button',{class:'btn primary',disabled:true,onclick:async()=>{
    if(!bytes||busy)return;busy=true;exportButton.disabled=true;status.textContent='Preparing your signed PDF…';output.replaceChildren();
    try {const doc=await PrismPDF.load(bytes),form=doc.getForm();for(const item of formValues){if(item.readOnly)continue;const field=form.getField(item.name);item.apply(field);}form.updateFieldAppearances();
      const embedded=new Map();for(const mark of marks){let png=embedded.get(mark.data);if(!png){png=await doc.embedPng(mark.data);embedded.set(mark.data,png);}const targets=mark.scope==='all'?doc.getPageIndices():mark.scope==='selected'?PrismPDF.pages(mark.range,doc.getPageCount(),false):[mark.page-1];for(const n of targets){const p=doc.getPage(n),box=p.getCropBox();if(p.getRotation().angle%360)throw Error('Page '+(n+1)+' is rotated. Signature export on rotated pages is not supported yet.');const x=box.x+mark.x*box.width,y=box.y+(1-mark.y-mark.h)*box.height,w=mark.w*box.width,ht=mark.h*box.height;p.drawImage(png,{x,y,width:w,height:ht});}}
      const blob=new Blob([await doc.save()],{type:'application/pdf'});const url=URL.createObjectURL(blob);output.replaceChildren(h('div',{class:'result-row'},h('span',{class:'grow'},'Ready to review'),h('a',{class:'btn',href:url,target:'_blank',rel:'noopener'},'Preview'),h('button',{class:'btn primary',onclick:()=>download(blob,filename.replace(/\.pdf$/i,'')+'-signed.pdf')},'Download PDF')));urls.push(url);status.textContent='Done. The original file is unchanged.';
    }catch(e){status.textContent=e.message||'Could not create PDF.';status.dataset.error='true';}finally{busy=false;exportButton.disabled=false;}
  }},'Create signed PDF');
  const formValues=[],urls=[];
  const tools=h('div',{class:'sign-side'},h('section',{class:'card'},h('h3',{},'1 · Open your PDF'),T.dropZone('Drop a PDF or browse','.pdf,application/pdf',false,async fs=>{
    try{if(fs[0].size>150*1024*1024)throw Error('Use a PDF under 150 MB.');bytes=await fs[0].arrayBuffer();filename=fs[0].name;const parsed=await PrismPDF.load(bytes);pageCount=parsed.getPageCount();formValues.length=0;formFields.replaceChildren();const F=self.PDFLib;
      for(const field of parsed.getForm().getFields()){const name=field.getName();let input,apply;if(field instanceof F.PDFTextField){input=h('input',{value:field.getText()||''});apply=f=>f.setText(input.value);}else if(field instanceof F.PDFCheckBox){input=h('input',{type:'checkbox',checked:field.isChecked()});apply=f=>input.checked?f.check():f.uncheck();}else if(field instanceof F.PDFDropdown||field instanceof F.PDFOptionList){input=h('select',{multiple:field.isMultiselect()},field.getOptions().map(option=>h('option',{value:option,selected:field.getSelected().includes(option)},option)));apply=f=>f.select([...input.selectedOptions].map(x=>x.value));}else if(field instanceof F.PDFRadioGroup){input=h('select',{},h('option',{value:''},'Not selected'),field.getOptions().map(option=>h('option',{value:option,selected:field.getSelected()===option},option)));apply=f=>input.value?f.select(input.value):f.clear();}else continue;input.disabled=field.isReadOnly();formFields.append(h('label',{class:'field'},h('span',{},name),input));formValues.push({name,apply,readOnly:field.isReadOnly()});}
      if(pdf)await pdf.destroy();pdf=await pdfjs.getDocument({data:new Uint8Array(bytes.slice(0))}).promise;pageNo=1;marks=[];await drawPage();place.disabled=false;exportButton.disabled=false;status.dataset.error='';status.textContent=filename+' · '+pageCount+' pages · '+formValues.length+' fillable fields';
    }catch(e){bytes=null;status.dataset.error='true';status.textContent=e.message||'Cannot open PDF.';place.disabled=exportButton.disabled=true;}
  })),h('section',{class:'card'},h('h3',{},'2 · Create your signature'),signature,typed,h('label',{class:'field'},h('span',{},'Or upload a signature image'),imageInput),h('button',{class:'btn small',onclick:()=>{pen.clearRect(0,0,600,180);typed.value='';drawn=false;}},'Clear signature'),h('label',{class:'field'},h('span',{},'Place on'),scope),range,place,h('button',{class:'btn small',onclick:()=>{const index=marks.findLastIndex(mark=>mark.page===pageNo);if(index>=0){marks.splice(index,1);drawMarks();}}},'Remove last placement')),h('section',{class:'card'},h('h3',{},'3 · Review & export'),h('p',{class:'sign-mini'},'A visual signature is not a certificate-based digital signature. Editing a signed PDF can invalidate an existing certificate signature.'),exportButton,status,output));
  target.append(h('div',{class:'sign-layout'},documentBox,tools),h('section',{class:'card sign-fields'},h('h3',{},'Fillable form fields'),formFields));
  let renderId=0, renderTask=null;
  async function drawPage(){if(!pdf)return;const id=++renderId;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}}const page=await pdf.getPage(pageNo);const viewport=page.getViewport({scale:1.35});if(id!==renderId)return;canvas.width=viewport.width;canvas.height=viewport.height;display=viewport;renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport});try{await renderTask.promise;}catch(e){if(e.name==='RenderingCancelledException')return;throw e;}if(id!==renderId)return;pageLabel.textContent='Page '+pageNo+' of '+pageCount;prev.disabled=pageNo===1;next.disabled=pageNo===pageCount;drawMarks();}
  function drawMarks(){pageBox.querySelectorAll('.sign-overlay').forEach(el=>el.remove());for(const mark of marks.filter(x=>x.scope==='all'||x.page===pageNo||(x.scope==='selected'&&(()=>{try{return PrismPDF.pages(x.range,pageCount,false).includes(pageNo-1);}catch{return false;}})()))){const el=h('div',{class:'sign-overlay',tabindex:0,'aria-label':'Signature. Drag or use arrow keys to move.'},h('img',{src:mark.data,alt:''}),h('span',{class:'resize','aria-hidden':'true'}));const paint=()=>{el.style.left=(mark.x*100)+'%';el.style.top=(mark.y*100)+'%';el.style.width=(mark.w*100)+'%';el.style.height=(mark.h*100)+'%';};paint();el.onpointerdown=e=>{if(e.target.classList.contains('resize'))return;const start=[e.clientX,e.clientY,mark.x,mark.y],box=pageBox.getBoundingClientRect();el.setPointerCapture(e.pointerId);el.onpointermove=event=>{mark.x=Math.max(0,Math.min(1-mark.w,start[2]+(event.clientX-start[0])/box.width));mark.y=Math.max(0,Math.min(1-mark.h,start[3]+(event.clientY-start[1])/box.height));paint();};el.onpointerup=()=>el.onpointermove=null;};const handle=el.querySelector('.resize');handle.onpointerdown=e=>{e.stopPropagation();const start=[e.clientX,e.clientY,mark.w,mark.h],box=pageBox.getBoundingClientRect();handle.setPointerCapture(e.pointerId);handle.onpointermove=event=>{const w=Math.max(.06,Math.min(1-mark.x,start[2]+(event.clientX-start[0])/box.width));mark.w=w;mark.h=Math.max(.02,Math.min(1-mark.y,w*180/600*box.width/box.height));paint();};handle.onpointerup=()=>handle.onpointermove=null;};el.onkeydown=e=>{const n=e.shiftKey?.02:.005;if(e.key==='Delete'||e.key==='Backspace'){marks.splice(marks.indexOf(mark),1);drawMarks();e.preventDefault();}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){mark.x=Math.max(0,Math.min(1-mark.w,mark.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0)));mark.y=Math.max(0,Math.min(1-mark.h,mark.y+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0)));paint();e.preventDefault();}};pageBox.append(el);}}
  dispose=()=>{renderId++;pdf?.destroy();urls.forEach(URL.revokeObjectURL);if(inputUrl)URL.revokeObjectURL(inputUrl);};
}
T.settings=await UI.theme();
addEventListener('hashchange',()=>render().catch(e=>{console.error(e);body.append(h('p',{class:'notice'},e.message||'Could not open tool.'));}));
render().catch(console.error);
